# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-05 21:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secondName', models.CharField(blank=True, db_index=True, default='', max_length=180, unique=True, verbose_name='\u0424\u0430\u043c\u0438\u043b\u0438\u044f')),
            ],
        ),
    ]
