# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-05 21:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personalities', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='secondName',
        ),
        migrations.AddField(
            model_name='person',
            name='second_name',
            field=models.CharField(db_index=True, default='', max_length=180, unique=True, verbose_name='\u0424\u0430\u043c\u0438\u043b\u0438\u044f'),
        ),
    ]
