# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-05 22:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Personalities', '0002_auto_20160206_0029'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': '\u041b\u0438\u0447\u043d\u043e\u0441\u0442\u044c', 'verbose_name_plural': '\u041b\u0438\u0447\u043d\u043e\u0441\u0442\u0438'},
        ),
    ]
